# JWT 签名使用的密钥，base64 格式字符串
JWT_SECRET = ""
# 微信回调域
WX_CALLBACK_URL = ""
# 微信公众平台 AppID
WX_APP_ID = ""
# 微信公众平台 AppSecret
WX_APP_SECRET = ""
# 微信公众平台 token
WX_TOKEN = ""
# 微信公众平台 EncodingAesKey，43 字节的无等号的 base64 格式字符串
WX_ENCODING_AES_KEY = ""