//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub room_id: i64,
    pub from_uid: i64,
    pub content: String,
    pub reply_msg_id: Option<i64>,
    pub status: i32,
    pub gap_count: Option<i32>,
    pub r#type: Option<i32>,
    pub extra: Option<Json>,
    pub create_time: TimeDateTime,
    pub update_time: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
