//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod black;
pub mod item_config;
pub mod message;
pub mod message_mark;
pub mod room;
pub mod user;
pub mod user_backpack;
pub mod wx_msg;
