//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::black::Entity as Black;
pub use super::item_config::Entity as ItemConfig;
pub use super::message::Entity as Message;
pub use super::message_mark::Entity as MessageMark;
pub use super::room::Entity as Room;
pub use super::user::Entity as User;
pub use super::user_backpack::Entity as UserBackpack;
pub use super::wx_msg::Entity as WxMsg;
