//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub name: Option<String>,
    pub avatar: Option<String>,
    pub sex: Option<i32>,
    #[sea_orm(unique)]
    pub open_id: String,
    pub last_opt_time: TimeDateTime,
    pub ip_info: Option<Json>,
    pub item_id: Option<i64>,
    pub status: Option<i32>,
    pub create_time: TimeDateTime,
    pub update_time: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
