//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_backpack")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub uid: i64,
    pub item_id: i32,
    pub status: i32,
    #[sea_orm(unique)]
    pub idempotent: String,
    pub create_time: TimeDateTime,
    pub update_time: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
